config/routes.rb
LoanIt::Application.routes.draw do
  resources :shares

  resources :resources

  resources :categories

  resources :group_users

  resources :groups

  resources :users

  resources :sessions

  resources :registrations
  
  match '/login', :to => "sessions#new", :as => :login
  match '/logout', :to => "sessions#destroy", :as => :logout

  match '/register', :to => "registrations#new", :as => :register
  
  match '/home', :to => "home#search", :as => :home

  root :to => 'home#search'

end

app/models/share.rb
class Share < ActiveRecord::Base
  attr_accessible :group_id, :resource_id, :user_id
  belongs_to :resource
  belongs_to :group

end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  # GET /shares
  # GET /shares.json
  def index
    @shares = Share.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shares }
    end
  end

  # GET /shares/1
  # GET /shares/1.json
  def show
    @share = Share.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @share }
    end
  end

  # GET /shares/new
  # GET /shares/new.json
  def new
    @share = Share.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @share }
    end
  end

  # GET /shares/1/edit
  def edit
    @share = Share.find(params[:id])
  end

  # POST /shares
  # POST /shares.json
  def create
    @share = Share.new(params[:share])

    respond_to do |format|
      if @share.save
        format.html { redirect_to @share, notice: 'Share was successfully created.' }
        format.json { render json: @share, status: :created, location: @share }
      else
        format.html { render action: "new" }
        format.json { render json: @share.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shares/1
  # PUT /shares/1.json
  def update
    @share = Share.find(params[:id])

    respond_to do |format|
      if @share.update_attributes(params[:share])
        format.html { redirect_to @share, notice: 'Share was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @share.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shares/1
  # DELETE /shares/1.json
  def destroy
    @share = Share.find(params[:id])
    @share.destroy

    respond_to do |format|
      format.html { redirect_to shares_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/views/shares/_form.html.erb
<%= form_for(@share) do |f| %>
  <% if @share.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@share.errors.count, "error") %> prohibited this share from being saved:</h2>

      <ul>
      <% @share.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :resource_id %><br />
    <%= f.number_field :resource_id %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.number_field :group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shares/edit.html.erb
<h1>Editing share</h1>

<%= render 'form' %>

<%= link_to 'Show', @share %> |
<%= link_to 'Back', shares_path %>

app/views/shares/index.html.erb
<h1>Listing shares</h1>

<table>
  <tr>
    <th>User</th>
    <th>Resource</th>
    <th>Group</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shares.each do |share| %>
  <tr>
    <td><%= share.user_id %></td>
    <td><%= share.resource_id %></td>
    <td><%= share.group_id %></td>
    <td><%= link_to 'Show', share %></td>
    <td><%= link_to 'Edit', edit_share_path(share) %></td>
    <td><%= link_to 'Destroy', share, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Share', new_share_path %>

app/views/shares/new.html.erb
<h1>New share</h1>

<%= render 'form' %>

<%= link_to 'Back', shares_path %>

app/views/shares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @share.user_id %>
</p>

<p>
  <b>Resource:</b>
  <%= @share.resource_id %>
</p>

<p>
  <b>Group:</b>
  <%= @share.group_id %>
</p>


<%= link_to 'Edit', edit_share_path(@share) %> |
<%= link_to 'Back', shares_path %>