config/routes.rb
LoanIt::Application.routes.draw do
  resources :shares

  resources :resources

  resources :categories

  resources :group_users

  resources :groups

  resources :users

  resources :sessions

  resources :registrations
  
  match '/login', :to => "sessions#new", :as => :login
  match '/logout', :to => "sessions#destroy", :as => :logout

  match '/register', :to => "registrations#new", :as => :register
  
  match '/home', :to => "home#search", :as => :home

  root :to => 'home#search'

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :owner_id

  has_many :shares
  has_many :shared_resources, :through => :shares, :source => :resource
  belongs_to :owner, :class_name => 'User'
  has_many :group_user
  has_many :users, :through => :group_user

  after_create do
    GroupUser.find_or_create_by_user_id_and_group_id(self.owner_id, self.id) 
  end
 
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @current_user = current_user
    if params[:mine]
      @groups = Group.where(:owner_id => @current_user.id)
    else
      @groups = Group.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= form_for(@group) do |f| 
  - if @group.errors.any? 
    #error_explanation
      %h2= pluralize(@group.errors.count, "error") + " prohibited this group from being saved:"

      %ul
        - @group.errors.full_messages.each do |msg| 
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
    -# .field
    -#   = f.label :owner_id
    -#   = f.number_field :owner_id
    .actions
      = f.submit

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Owner</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= group.name %></td>
    <td><%= group.owner_id %></td>
    <td><%= link_to 'Show', group %></td>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group', new_group_path %>

app/views/groups/index.html.haml
%h1 Listing groups

%table
  %tr
    %th Name
    %th Owner
    %th 
    %th
    %th
  - @groups.each do |group|
    %tr
      %td= group.name
      %td= group.owner.name
      %td= link_to 'Show', group
      %td= link_to 'Edit', edit_group_path(group)
      %td= link_to 'Destroy',group ,method: :delete
<!--     <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->

%br/
= link_to 'Create a new Group', new_group_path

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/new.html.haml
%h1 New group

= render 'form' 
= link_to 'Back', groups_path 

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>

<p>
  <b>Owner:</b>
  <%= @group.owner_id %>
</p>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>