config/routes.rb
LoanIt::Application.routes.draw do
  resources :shares

  resources :resources

  resources :categories

  resources :group_users

  resources :groups

  resources :users

  resources :sessions

  resources :registrations
  
  match '/login', :to => "sessions#new", :as => :login
  match '/logout', :to => "sessions#destroy", :as => :logout

  match '/register', :to => "registrations#new", :as => :register
  
  match '/home', :to => "home#search", :as => :home

  root :to => 'home#search'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :resource
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :owner_id

  has_many :shares
  has_many :shared_resources, :through => :shares, :source => :resource
  belongs_to :owner, :class_name => 'User'
  has_many :group_user
  has_many :users, :through => :group_user

  after_create do
    GroupUser.find_or_create_by_user_id_and_group_id(self.owner_id, self.id) 
  end
 
  
end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
  attr_accessible :group_id, :user_id
  
  belongs_to :group
  belongs_to :user

end

app/models/resource.rb
class Resource < ActiveRecord::Base
  attr_accessible :available, :category_id, :description, :name, :owner_groups_searchable, :owner_id, :publicly_searchable

  has_many :shares
  has_many :shared_groups, :through => :shares, :source => :group
  belongs_to :category
  belongs_to :user, :foreign_key => :owner_id

  define_index do
    indexes :name
    indexes description

    has shared_groups(:id), :as => :shared_group_ids
    has :publicly_searchable
    
    set_property :delta => true
  end

end

app/models/share.rb
class Share < ActiveRecord::Base
  attr_accessible :group_id, :resource_id, :user_id
  belongs_to :resource
  belongs_to :group

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name

  validates :email, :uniqueness => true
  
  has_many :resource ,:foreign_key => :owner_id
#  has_many :owned_groups, :forei gn_key => :owner_id, :source => :group
  has_many :group_user
  has_many :groups, :through => :group_user
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @current_user = current_user
    if params[:mine]
      @groups = Group.where(:owner_id => @current_user.id)
    else
      @groups = Group.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def search
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  # GET /shares
  # GET /shares.json
  def index
    @shares = Share.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shares }
    end
  end

  # GET /shares/1
  # GET /shares/1.json
  def show
    @share = Share.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @share }
    end
  end

  # GET /shares/new
  # GET /shares/new.json
  def new
    @share = Share.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @share }
    end
  end

  # GET /shares/1/edit
  def edit
    @share = Share.find(params[:id])
  end

  # POST /shares
  # POST /shares.json
  def create
    @share = Share.new(params[:share])

    respond_to do |format|
      if @share.save
        format.html { redirect_to @share, notice: 'Share was successfully created.' }
        format.json { render json: @share, status: :created, location: @share }
      else
        format.html { render action: "new" }
        format.json { render json: @share.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shares/1
  # PUT /shares/1.json
  def update
    @share = Share.find(params[:id])

    respond_to do |format|
      if @share.update_attributes(params[:share])
        format.html { redirect_to @share, notice: 'Share was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @share.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shares/1
  # DELETE /shares/1.json
  def destroy
    @share = Share.find(params[:id])
    @share.destroy

    respond_to do |format|
      format.html { redirect_to shares_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoanIt</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br />
    <%= f.number_field :owner_id %>
  </div>
  <div class="field">
    <%= f.label :publicly_searchable %><br />
    <%= f.text_field :publicly_searchable %>
  </div>
  <div class="field">
    <%= f.label :owner_groups_searchable %><br />
    <%= f.check_box :owner_groups_searchable %>
  </div>
  <div class="field">
    <%= f.label :available %><br />
    <%= f.check_box :available %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Category</th>
    <th>Owner</th>
    <th>Publicly searchable</th>
    <th>Owner groups searchable</th>
    <th>Available</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resources.each do |resource| %>
  <tr>
    <td><%= resource.name %></td>
    <td><%= resource.description %></td>
    <td><%= resource.category_id %></td>
    <td><%= resource.owner_id %></td>
    <td><%= resource.publicly_searchable %></td>
    <td><%= resource.owner_groups_searchable %></td>
    <td><%= resource.available %></td>
    <td><%= link_to 'Show', resource %></td>
    <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
    <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @resource.name %>
</p>

<p>
  <b>Description:</b>
  <%= @resource.description %>
</p>

<p>
  <b>Category:</b>
  <%= @resource.category_id %>
</p>

<p>
  <b>Owner:</b>
  <%= @resource.owner_id %>
</p>

<p>
  <b>Publicly searchable:</b>
  <%= @resource.publicly_searchable %>
</p>

<p>
  <b>Owner groups searchable:</b>
  <%= @resource.owner_groups_searchable %>
</p>

<p>
  <b>Available:</b>
  <%= @resource.available %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>